name: CI - Serenity with Cucumber

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up JDK (Java Development Kit)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Cache Maven dependencies to speed up build
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Install Google Chrome
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    # Install ChromeDriver
    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        echo "Chrome Version: $CHROME_VERSION"
        CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        echo "ChromeDriver Version: $CHROME_DRIVER_VERSION"
        curl -sS -o /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
        unzip /tmp/chromedriver.zip -d /usr/local/bin/
        rm /tmp/chromedriver.zip
        sudo chmod +x /usr/local/bin/chromedriver

    # Install Maven dependencies
    - name: Install Maven Dependencies
      run: mvn install --no-transfer-progress --quiet

    # Run Tests with Maven (Serenity and Cucumber)
    - name: Run Tests
      run: mvn clean verify -Dwebdriver.chrome.driver=chromedriver

    # Publish Serenity Reports as an Artifact
    - name: Upload Serenity Reports
      uses: actions/upload-artifact@v3
      with:
        name: serenity-reports
        path: target/site/serenity
